### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by izgzhen** [MarkGaox/soot-skeleton#1]
I can't reproduce the exception you mentioned since I don't know the steps.

**Comment by MarkGaox** [comment]
I basically just run the Analysis.java file with Intellij's configuration.
![image](https://user-images.githubusercontent.com/32374858/65434057-04360d80-ddd3-11e9-8e57-961d0acbfec2.png)

And then I found the following error. 
Exception in thread "main" java.lang.UnsupportedClassVersionError: soot/options/Options : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at SootExample.Analysis.main(Analysis.java:27)

And the following two photos are my check for the JDK.
![Screen Shot 2019-09-23 at 7 25 01 AM](https://user-images.githubusercontent.com/32374858/65434233-570fc500-ddd3-11e9-94c7-ac78154af129.png)
![Screen Shot 2019-09-23 at 7 25 18 AM](https://user-images.githubusercontent.com/32374858/65434234-570fc500-ddd3-11e9-8f05-cf5043524cd7.png)

**Comment by MarkGaox** [comment]
It's solved. This error happens because I didn't update the Intellij to the newest version. And now it works. Thanks!

**Comment by izgzhen** [comment]
That's great!

By the way, you should consider using maven or other similar build systems once you got some time.
