### ISSUE TITLE
Exception when parse Java code that has "System.out.print()".

### ISSUE THREAD

**Issue by MarkGaox** [MarkGaox/soot-skeleton#8]

**Comment by MarkGaox** [comment]
Error: Failed to load java.lang.CharSequence.
```
public void overloadTester() {
        String a = "abc";
        System.out.println(a);  // error at here
        overload((byte)1);
        overload((short)1);
        overload(1);
        overload(1L);
        overload(1.0f);
        overload(1.0);
        overload('1');
        overload(true);
}    
```
AppTest fails when target has  "System.out.println(a); " statement.

**Comment by MarkGaox** [comment]
Related issue: https://github.com/Sable/soot/issues/896

**Comment by MarkGaox** [comment]
run ```make test``` to see this error. 
Here is the error.
![Screenshot 2019-11-03 16 01 10](https://user-images.githubusercontent.com/32374858/68094251-42ebc880-fe53-11e9-91b4-b194348dcac2.png)
To see more information about the correct place that generates this error, click debug at the upper right corner of the IDE.
![Screenshot 2019-11-03 16 02 35](https://user-images.githubusercontent.com/32374858/68094264-5f880080-fe53-11e9-80a4-d7929faa2cd2.png)

**Comment by izgzhen** [comment]
I am actually having a different error msg:

```
[INFO] Running unit.AppTest
javaVersion=11.0.3
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.042 s <<< FAILURE! - in unit.AppTest
[ERROR] CommandLineTest(unit.AppTest)  Time elapsed: 0.013 s  <<< ERROR!
Exception.JDKException: Incorrect JDK version: 11.0.3. Please check again.
	at unit.AppTest.CommandLineTest(AppTest.java:10)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   AppTest.CommandLineTest:10 » JDK Incorrect JDK version: 11.0.3. Please check a...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
```

**Comment by izgzhen** [comment]
My problem should be irrelevant -- I installed a different version of maven.

**Comment by izgzhen** [comment]
Okay, after setting `JAVA_HOME` correctly with `jenv`, I reproduced your error

**Comment by izgzhen** [comment]
Backtrace for the first error:

```
java.lang.Error: Error: Failed to load java.lang.CharSequence.

	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:109)
....
	at soot.JavaClassSource.resolve(JavaClassSource.java:66)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.bringToSignatures(SootResolver.java:279)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:172)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:927)
	at Analysis.Analyzer.testConfigSpace(Analyzer.java:102)
	at Analysis.Analyzer.<init>(Analyzer.java:23)
	at edu.washington.cs.skeleton.Skeleton.mostNarrowParser(Skeleton.java:106)
	at edu.washington.cs.skeleton.Skeleton.<init>(Skeleton.java:67)
	at edu.washington.cs.skeleton.App.main(App.java:62)
	at unit.AppTest.CommandLineTest(AppTest.java:10)
...
```

**Comment by izgzhen** [comment]
![Screen Shot 2019-11-03 at 5 36 15 PM](https://user-images.githubusercontent.com/7168454/68095687-7123d500-fe60-11e9-9e2c-f0d700e99b22.png)

**Comment by izgzhen** [comment]
This is apparently wrong -- `DemoClass.class` is not in `process_dir`, which is `test-resource` folder.

**Comment by izgzhen** [comment]
So the first problem is: you should manage your test dependencies more carefully with `Makefile`
